#include "constants.h"

const QString Constants::AUTHORIZATION_TOKEN = "71a3e5fe1b1899a3ec9541f735a1f2e14335fce9a35bca14b66709bbd95d6";

const QString Constants::API_BASE_URL = "https://localhost:7276/api";

const QString Constants::URL_USER_CHANGE_PASSWORD = QString("%1/User/change-password").arg(API_BASE_URL);
const QString Constants::URL_USER_CREATE = QString("%1/User/create").arg(API_BASE_URL);
const QString Constants::URL_USER_DELETE = QString("%1/User/delete").arg(API_BASE_URL);
const QString Constants::URL_ACCOUNT_DELETE = QString("%1/User/delete-account").arg(API_BASE_URL);
const QString Constants::URL_USER_RESTORE = QString("%1/User/restore").arg(API_BASE_URL);
const QString Constants::URL_USER_SIGNIN = QString("%1/User/signin").arg(API_BASE_URL);
const QString Constants::URL_USER_UPDATE = QString("%1/User/update").arg(API_BASE_URL);
const QString Constants::URL_USER_GET_BY_ID = QString("%1/User/get-by-id").arg(API_BASE_URL);
const QString Constants::URL_USER_GET_LIST = QString("%1/User/get-list").arg(API_BASE_URL);
const QString Constants::URL_PRODUCT_CREATE = QString("%1/Product/create").arg(API_BASE_URL);
const QString Constants::URL_PRODUCT_DELETE = QString("%1/Product/delete").arg(API_BASE_URL);
const QString Constants::URL_PRODUCT_RESTORE = QString("%1/Product/restore").arg(API_BASE_URL);
const QString Constants::URL_PRODUCT_UPDATE = QString("%1/Product/update").arg(API_BASE_URL);
const QString Constants::URL_PRODUCT_GET_BY_ID = QString("%1/Product/get-by-id").arg(API_BASE_URL);
const QString Constants::URL_PRODUCT_GET_LIST = QString("%1/Product/get-list").arg(API_BASE_URL);

const std::vector<QString> Constants::COUNTRY_LIST = {
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "México",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
};
